// Bank soal pretest & posttest (25 soal simulasi).
// Dipakai UjianPage, dan jumlahnya dipakai halaman Pretest Selesai.
export const bankSoal = [
  { id:1, pertanyaan:'Manakah pernyataan yang paling tepat mengenai perubahan iklim global?', pilihan:['Perubahan iklim hanya terjadi di daerah tropis','Peningkatan suhu bumi akibat emisi gas rumah kaca','Perubahan iklim tidak berpengaruh pada curah hujan','Perubahan iklim adalah fenomena alam biasa'], kunci:1 },
  { id:2, pertanyaan:'Apa yang dimaksud dengan efek rumah kaca?', pilihan:['Proses pertanian di dalam rumah kaca','Fenomena memanasnya Bumi akibat gas atmosfer menyerap radiasi inframerah','Penggunaan energi surya untuk rumah tangga','Metode penyimpanan karbon di lautan'], kunci:1 },
  { id:3, pertanyaan:'Gas apakah yang paling banyak berkontribusi terhadap pemanasan global?', pilihan:['Oksigen (O₂)','Nitrogen (N₂)','Karbon Dioksida (CO₂)','Hidrogen (H₂)'], kunci:2 },
  { id:4, pertanyaan:'Apa dampak utama pemanasan global terhadap laut?', pilihan:['Air laut menjadi lebih dingin','Permukaan air laut naik akibat mencairnya es kutub','Jumlah ikan meningkat drastis','Salinitas air laut menurun tajam'], kunci:1 },
  { id:5, pertanyaan:'Organisasi PBB yang menangani isu perubahan iklim adalah...', pilihan:['WHO','UNICEF','IPCC','UNESCO'], kunci:2 },
  { id:6, pertanyaan:'Apa perbedaan utama antara cuaca dan iklim?', pilihan:['Cuaca bersifat jangka pendek, iklim jangka panjang','Keduanya sama saja','Iklim hanya berlaku di kutub','Cuaca tidak dapat berubah'], kunci:0 },
  { id:7, pertanyaan:'Lapisan atmosfer yang melindungi Bumi dari radiasi UV adalah...', pilihan:['Troposfer','Stratosfer (Lapisan Ozon)','Mesosfer','Termosfer'], kunci:1 },
  { id:8, pertanyaan:'Apa yang menyebabkan lubang ozon?', pilihan:['Peningkatan oksigen','Penggunaan CFC dan halokarbon','Peningkatan nitrogen','Penurunan suhu global'], kunci:1 },
  { id:9, pertanyaan:'El Niño adalah fenomena yang terjadi di...', pilihan:['Samudra Atlantik','Samudra Hindia','Samudra Pasifik','Laut Mediterania'], kunci:2 },
  { id:10, pertanyaan:'Dampak El Niño di Indonesia umumnya berupa...', pilihan:['Curah hujan meningkat drastis','Kekeringan berkepanjangan','Suhu menurun drastis','Badai salju'], kunci:1 },
  { id:11, pertanyaan:'Apa yang dimaksud dengan adaptasi perubahan iklim?', pilihan:['Menghentikan semua aktivitas industri','Menyesuaikan diri dengan dampak perubahan iklim','Mengabaikan perubahan iklim','Memindahkan semua penduduk ke kutub'], kunci:1 },
  { id:12, pertanyaan:'Mitigasi perubahan iklim bertujuan untuk...', pilihan:['Meningkatkan emisi gas rumah kaca','Mengurangi penyebab perubahan iklim','Mempercepat pemanasan global','Menghilangkan semua gas di atmosfer'], kunci:1 },
  { id:13, pertanyaan:'Sektor mana yang menyumbang emisi CO₂ terbesar?', pilihan:['Pertanian','Energi dan transportasi','Perikanan','Pariwisata'], kunci:1 },
  { id:14, pertanyaan:'Apa fungsi utama BMKG?', pilihan:['Mengelola keuangan negara','Monitoring meteorologi, klimatologi, dan geofisika','Mengatur lalu lintas udara','Mengelola sumber daya air'], kunci:1 },
  { id:15, pertanyaan:'Alat untuk mengukur curah hujan disebut...', pilihan:['Termometer','Barometer','Penakar hujan (Rain gauge)','Anemometer'], kunci:2 },
  { id:16, pertanyaan:'Apa yang dimaksud dengan carbon footprint?', pilihan:['Jejak kaki di pasir','Total emisi gas rumah kaca yang dihasilkan oleh individu/organisasi','Jenis bahan bakar fosil','Metode pertanian organik'], kunci:1 },
  { id:17, pertanyaan:'Pohon berperan penting dalam mengurangi pemanasan global karena...', pilihan:['Menghasilkan CO₂','Menyerap CO₂ dan menghasilkan O₂','Meningkatkan suhu tanah','Mengurangi curah hujan'], kunci:1 },
  { id:18, pertanyaan:'Energi terbarukan yang paling banyak digunakan di dunia adalah...', pilihan:['Energi nuklir','Energi surya dan angin','Energi batu bara','Energi minyak bumi'], kunci:1 },
  { id:19, pertanyaan:'La Niña umumnya menyebabkan di Indonesia...', pilihan:['Kekeringan panjang','Curah hujan di atas normal','Suhu sangat panas','Gempa bumi'], kunci:1 },
  { id:20, pertanyaan:'Apa yang dimaksud dengan Iklim Muson?', pilihan:['Iklim yang hanya memiliki 1 musim','Iklim dengan pergantian musim hujan dan kemarau akibat angin muson','Iklim di daerah kutub','Iklim tanpa hujan'], kunci:1 },
  { id:21, pertanyaan:'Deforestasi berkontribusi terhadap pemanasan global karena...', pilihan:['Menambah jumlah pohon','Mengurangi penyerapan CO₂ dan melepaskan karbon tersimpan','Menurunkan suhu global','Meningkatkan produksi oksigen'], kunci:1 },
  { id:22, pertanyaan:'Perjanjian internasional tentang perubahan iklim yang ditandatangani tahun 2015 adalah...', pilihan:['Protokol Kyoto','Perjanjian Paris','Perjanjian Montreal','Konvensi Basel'], kunci:1 },
  { id:23, pertanyaan:'Apa dampak kenaikan permukaan air laut?', pilihan:['Daratan bertambah luas','Banjir rob dan tenggelamnya pulau kecil','Suhu laut menurun','Ikan bertambah banyak'], kunci:1 },
  { id:24, pertanyaan:'Indeks Kualitas Udara (AQI) yang menunjukkan "Tidak Sehat" berada pada rentang...', pilihan:['0-50','51-100','101-150','151-200'], kunci:3 },
  { id:25, pertanyaan:'Apa peran generasi muda dalam menghadapi perubahan iklim?', pilihan:['Tidak perlu peduli karena bukan urusan mereka','Aktif dalam edukasi, advokasi, dan aksi nyata pelestarian lingkungan','Hanya mengandalkan pemerintah','Menghindari semua teknologi modern'], kunci:1 },
];
